name: Release Assets

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create ZIP file
      run: |
        mkdir release
        zip -r release/code.zip src/

    - name: Create tar.gz file
      run: |
        tar -czf release/code.tar.gz .

    - name: Crear archivo TAR.BZ2
      run: |
        tar -cjf release/code.tar.bz2 .

    - name: Subir archivos como release assets
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
