name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          zip -r source_code.zip .  # Create ZIP file of the source code
  
      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          files: |
            source_code.zip
